# name of the action
name: publish

# trigger on push events with branch master
on:
  push:
    branches: [ main ]

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: golang:1.17
    steps:
    - name: clone
      uses: actions/checkout@v2
      with:
        # ensures we fetch tag history for the repository
        fetch-depth: 0

    - name: build
      env:
        GOOS: linux
        CGO_ENABLED: '0'
      run: |
        make build-static-ci

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.actor }}/vela-docker
        cache: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
